# Generated by Django 4.2.9 on 2026-05-27 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('file_uploaded', 'File Uploaded'), ('ingestion_started', 'Ingestion Started'), ('ingestion_completed', 'Ingestion Completed'), ('ingestion_failed', 'Ingestion Failed'), ('record_flagged', 'Record Flagged'), ('record_approved', 'Record Approved'), ('record_rejected', 'Record Rejected'), ('record_locked', 'Record Locked'), ('record_edited', 'Record Edited'), ('note_added', 'Note Added'), ('bulk_approved', 'Bulk Approved'), ('bulk_rejected', 'Bulk Rejected')], max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=100)),
                ('target_repr', models.CharField(blank=True, max_length=500)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
