# Generated by Django 4.2.9 on 2026-05-27 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel/Procurement'), ('utility_electricity', 'Utility Electricity'), ('corporate_travel', 'Corporate Travel')], max_length=50)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_path', models.FileField(max_length=500, upload_to='uploads/%Y/%m/')),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('flagged_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('ingestion_timestamp', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('detected_columns', models.JSONField(default=list)),
                ('column_mapping_used', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'source_files',
                'ordering': ['-ingestion_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged - Needs Attention'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('scope_category', models.CharField(choices=[('scope_1', 'Scope 1 - Direct Emissions'), ('scope_2', 'Scope 2 - Indirect (Energy)'), ('scope_3', 'Scope 3 - Value Chain')], max_length=20)),
                ('activity_category', models.CharField(choices=[('stationary_combustion', 'Stationary Combustion'), ('mobile_combustion', 'Mobile Combustion'), ('purchased_electricity', 'Purchased Electricity'), ('business_travel', 'Business Travel'), ('employee_commute', 'Employee Commute'), ('upstream_transport', 'Upstream Transport')], max_length=50)),
                ('source_type', models.CharField(max_length=50)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=50)),
                ('normalized_unit', models.CharField(blank=True, max_length=50)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('source_identifier', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('cost_center', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=200)),
                ('calculated_emissions', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('calculated_emissions_unit', models.CharField(default='kgCO2e', max_length=20)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_reasons', models.JSONField(default=list)),
                ('validation_errors', models.JSONField(default=list)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('analyst_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_reason', models.TextField(blank=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('original_payload', models.JSONField(default=dict)),
                ('row_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='emissions.emissionrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.sourcefile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant')),
            ],
            options={
                'db_table': 'emission_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='emission_re_tenant__615123_idx'), models.Index(fields=['tenant', 'scope_category'], name='emission_re_tenant__37715d_idx'), models.Index(fields=['source_file', 'status'], name='emission_re_source__426923_idx'), models.Index(fields=['suspicious_flag'], name='emission_re_suspici_c4f3d6_idx'), models.Index(fields=['activity_date'], name='emission_re_activit_afed01_idx')],
            },
        ),
    ]
